#!/usr/bin/env python

################################################################
#
# CGC_main.py  # Compare Gene Calls Main
#
# Programmer: Carol Zhou
#
# Description:  Accepts a list of input files, each comprising a set of
#    gene calls from a given gene caller program (e.g., Prodigal, Glimmer,
#    GeneMark, RAST, PHANOTATE).  Outputs comparisons accross the gene calls. 
#    Note:  The input files are re-formatted using CGC_parser.py, so that
#    they have a common format and identify the gene caller in the comments
#    at the top of the file.
#
################################################################

# This code was developed by Carol L. Ecale Zhou at Lawrence Livermore National Laboratory.
# THIS CODE IS COVERED BY THE BSD LICENSE. SEE INCLUDED FILE BSD.pdf FOR DETAILS.

import os

PHATE_PIPELINE = True  # Running this code within the PhATE pipeline. Set this to False if running code independently
#PHATE_PIPELINE = False

##### VERBOSITY

# Note: These environment variables are set in CGC_parser.py, which is usually run before CGC_main.py
# Therefore, if you have not run CGC_parser.py first, then you need to set these environment variables
# by hand at the command line. Set env vars to 'True' or 'False' as strings, not booleans.

if PHATE_PIPELINE:
    CGC_WARNINGS = os.environ["CGC_WARNINGS"]
    CGC_MESSAGES = os.environ["CGC_MESSAGES"]
    CGC_PROGRESS = os.environ["CGC_PROGRESS"]
else:
    CGC_WARNINGS = 'True'
    CGC_MESSAGES = 'True'
    CGC_PROGRESS = 'True'

#DEBUG = True
DEBUG = False

##### Import modules

import sys
import re
import string
import copy
from subprocess import call
import CGC_geneCall
import CGC_compare
import datetime

##### FILES

CODE_BASE = "CGC_main"
CODE_FILE = CODE_BASE + ".py"
LOG_FILE  = CODE_BASE + ".log"
OUT_FILE  = CODE_BASE + ".out"

infile = ""
#OUT = open(OUT_FILE,"w") 
LOG1 = open(LOG_FILE,"w")

##### PATTERNS

p_comment  = re.compile('^#')
p_order    = re.compile('Order')

##### CONSTANTS

HELP_STRING = "This code inputs a list of at least 2 files comprising gene calls (generated by a gene caller program) and outputs the genes that are in common and unique with respect to each caller.  Type: python " + CODE_FILE + " usage|input|detail for more information\n"

USAGE_STRING = "Usage:  python " + CODE_FILE + " <infile>n\n"

INPUT_STRING = "Input for " + CODE_FILE + " comprises a list of path/filenames comprising outputs generated by gene caller programs, with each separated by a single space. The output files are to have been prepared using code \"CGC_parser.py\" to assure that they have a common pre-defined format and indicate the name of the gene caller in the comments section.\nExample:  python " + CODE_FILE + " genemark.calls prodigal.calls\n"

INFO_STRING = "This code currently supports the following gene callers:  GeneMark, Glimmer, Prodigal, RAST, and PHANOTATE. For more information regarding input to " + CODE_FILE + ", type:  " + CODE_FILE + " input"

##### GET INPUT PARAMETERS

p_log = re.compile("log=([\w\d\_\-\.\\\/]+)")
fileSet = []
argCount = len(sys.argv)
if DEBUG:
    print "sys.argv is", sys.argv
if argCount > 1:

    if PHATE_PIPELINE:  # First parameter is "log=<logFile>", and remaining parameters are genecall files to compare
        if argCount > 2:
            match = re.search(p_log, sys.argv[1].lower())
            if match:
                LOG_FILE = match.group(1)
                LOG2 = open(LOG_FILE,"w")
                LOG2.write("%s%s\n" % ("Opening log at ",datetime.datetime.now()))
                if DEBUG:
                    print "DEBUG CGC_main: LOG2 has been opened"
            else:
                print "ERROR: CGC_main.py expects name of log file as first input parameter. Parameter was:", sys.argv[1]
            fileSet = sys.argv[2:]  # collect remaining command-line arguments
            if DEBUG:
                print "DEBUG CGC_main: fileSet is", fileSet
        else:
            print "ERROR: CGC_main says, insufficient arguments provided"

    else:  # "Help" input parameters should only be encountered if running code independently at command line
        match = re.search("help", sys.argv[1].lower())  
        if match:
            print HELP_STRING
            LOG1.close(); exit(0)

        match = re.search("input", sys.argv[1].lower())
        if match:
            print INPUT_STRING
            LOG1.close(); exit(0)

        match = re.search("usage", sys.argv[1].lower())
        if match:
            print USAGE_STRING
            LOG1.close(); exit(0)

        match = re.search("detail", sys.argv[1].lower())
        if match:
            print INFO_STRING
            LOG1.close(); exit(0)

        match = re.search("info", sys.argv[1].lower())
        if match:
            print INFO_STRING
            LOG1.close(); exit(0)
        else:
            fileSet = sys.argv[1:]  # skip 0th element = name of code

else:
    LOG1.write("%s\n" % ("Incorrect number of command-line arguments provided"))
    print USAGE_STRING
    LOG1.close(); exit(0)

##### BEGIN MAIN 

count = 0
callerList = []
callSet_obj = CGC_geneCall.GeneCallSet()

# For each user-provided gene call file, create a call set and add to list of call sets

if CGC_PROGRESS == 'True':
    print "CGC: Iterating through fileSet..."
if PHATE_PIPELINE:
    LOG2.write("%s%s\n" % ("Iteraing through fileSet at ",datetime.datetime.now()))
    LOG2.write("%s%s\n" % ("fileSet is ",fileSet))

for geneFile in fileSet:
    callSet = copy.deepcopy(callSet_obj)
    if PHATE_PIPELINE:
        LOG2.write("%s%s\n" % ("Processing geneFile ",geneFile))
    geneFile_handle = open(geneFile,"r")
    if CGC_MESSAGES == 'True':
        print "Adding Calls from file", geneFile
    callSet.AddGeneCalls(geneFile_handle) #*** check this
    geneFile_handle.close()
    callerList.append(callSet)  #*** check this
    LOG2.write("%s%s\n" % ("callerList is ",callerList))

if CGC_MESSAGES == 'True':
    print "Main: callerList is", 
    for caller in callerList:
        print caller.geneCaller, ', ',
    print 

if PHATE_PIPELINE:
    callers = ''
    for caller in callerList:
        callerString = caller.geneCaller + ' '
        callers += callerString
    LOG2.write("%s%s\n" % ("callerList is ",callers))

# Check
if DEBUG:
    print "\n******************Original Lists:"
    for caller in callerList:
        caller.PrintAll()
        print

# Sort calls in each list

if CGC_PROGRESS == 'True':
    print "Main: Sorting gene calls for each caller..."
if PHATE_PIPELINE:
    LOG2.write("%s\n" % ("Main: Sorting gene calls for each caller"))

for caller in callerList:
    caller.SortGeneCalls()

# Check
if DEBUG:
    print "\n******************Sorted Lists:"
    for caller in callerList:
        caller.PrintAll()
        print

# Compare across the call sets

if CGC_PROGRESS == 'True':
    print "Main: Comparing accross the call sets..."
if PHATE_PIPELINE:
    LOG2.write("%s\n" % ("Main: Comparing across the call sets..."))

compareGCs = CGC_compare.Comparison()
if PHATE_PIPELINE:
    LOG2.write("%s\n" % ("Merging..."))
for caller in callerList:
    compareGCs.Merge(caller.geneCallList)
if PHATE_PIPELINE:
    LOG2.write("%s\n" % ("Comparing..."))
compareGCs.Compare()
if PHATE_PIPELINE:
    LOG2.write("%s\n" % ("Identifying common core..."))
compareGCs.IdentifyCommonCore()
if PHATE_PIPELINE:
    LOG2.write("%s\n" % ("Printing report..."))
compareGCs.PrintReport()

# Check
if DEBUG:
    compareGCs.PrintAll()

if CGC_PROGRESS == 'True':
    print "CGC: complete."
if PHATE_PIPELINE:
    LOG2.write("%s%s\n" % ("CGC: complete at ",datetime.datetime.now()))

##### CLEAN UP

#OUT.close()
#LOG.close()
if PHATE_PIPELINE:
    LOG2.close()
else:
    LOG1.close()
